### ISSUE TITLE
TypeError: pol2cart() missing 1 required positional argument: 'phi'

### ISSUE THREAD

**Issue by TextZip** [anonanon02/Biped#8]
Hi @daviddoo02 , 

Thanks a lot for this amazing work. I went through the Leg Static Analysis notebook and tried running it using Google Colab. It looks like the pol2cart() method requires three parameters and only two are being provided. 

Got the following error:
```bash
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-7e677afad58a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 j1,j2,j3,j4,j5 = forward_kinematics(60, 120)
      2 
      3 # Create 3D plot
      4 fig = plt.figure()
      5 ax = fig.add_subplot()

[<ipython-input-7-282f80d4137f>](https://localhost:8080/#) in forward_kinematics(th1, th2)
     24 
     25     j1 = np.array([0, 0])
---> 26     j2 = j1 + pol2cart(l1, th1)
     27     j3 = j2 + pol2cart(l2, th1 + th2)
     28 

TypeError: pol2cart() missing 1 required positional argument: 'phi'
```

Could you also please give some information about what the static analysis is being used for here ? I have seen some static analysis tools in CAD software like solidworks and such but I never came across this pythonic way of doing things. 

TIA

**Comment by daviddoo02** [comment]
Hey @TextZip, the reason it's asking for 3 arguments is because I was trying to get it to work in 3D. I was running a static analysis using anastruct to calculate how to scale each linkages so that my servos (40 & 80 kgcm) can support it. The number it gave me wasn't quite as reliable as I expected so I went with a best guess and figure it out experimentally.
